### ISSUE TITLE
Amazing work！Want your code.

### ISSUE THREAD

**Issue by YaoXinZhi** [yaqingwang/WeFEND-AAAI20#1]
This is a very meaningful work, we have carefully read your paper and now, we are thinking if it is possible that you can share your experimental code.
Best wishes.

**Comment by yaqingwang** [comment]
Thanks for your interest in our paper. 
Because our model has already been employed into the fake news detection system of the wechat team and thus we will further discuss with them to confirm whether we can make the code public.  For encouraging the research on weak supervision for fake news detection, we will publish the dataset of this paper.

**Comment by YaoXinZhi** [comment]
Thank you for your reply.
Sincerely hope that 'OK' will be the result of your discussion.

**Comment by SudharshanShanmugasundaram** [comment]
Even I read the paper and found the work to be really interesting. Any updates on the discussion with your team. It would be very helpful if the code is made public because this will encourage many others to research in this area.

**Comment by JohannesTK** [comment]
+1

**Comment by ceinzx** [comment]
+1

**Comment by pmacinec** [comment]
Hello.

Firstly, I admire the interesting work!

Any updates on this? Will at least data be available? Thanks.

**Comment by dqksnow** [comment]
Hope you can share the code or data!

**Comment by yaqingwang** [comment]
Thanks for waiting!  Then data is finally public!

FYI, we collect more data and decide to make all the data public. Hope this helps with your research.
The class distribution is imbalanced, feel free to adjust the distribution as you need.
